mysql:
  user: ''
  password: ''
  host: localhost
  database: ''
  port: 3306
  prefix: ''
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
  savesPerDay: 64
bastions:
#The first bastion in this list will be used as the default type
#This only really matters the first time your start it up when converting from old bastion
#All bastions in the db will be flagged as, in this instance, citybastion
  basic:
    block:
      material: SPONGE
      durability: 0
      name: Bastion
      lore: 
        - This bastion will protect you from grief
        - It will also block pearls when they land
        - As well as stop elytra
    squarefield: true
    effectRadius: 10
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.75
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 5
    blocksToErode: -1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: false
    pearls:
      block: true
      blockMidair: false
      scaleFactor: 1
      requireMaturity: true
      consumeOnBlock: false
      damageFirstBastion: true
    elytra:
      block: true
      scaleFactor: 0.25
      requireMaturity: true
      destroyOnBlock: false
      damageOnBlock: true
      explodeOnBlock: true
      explodeOnBlockStrength: 0
