free_tppearl: true
autofree_worldborder: true
prison_musthotbar: true
prison_stealing: true
damagelog_min: 1
damagelog_ticks: 600
summon_damage_radius: 20
summon_damage_ticks: 20
summon_damage_amt: 2
kickMessage: You have too many imprisoned alts! If you think this is an error modmail /r/civclassics
ppsaveticks: 1200
debug: false
alts:
  enabled: true
  max_imprisoned: 1
prison:
  reset_bed: false
  world: world_the_end
  clearinventoryonsummon: true
  ppreturn_kill: false
  ppsummonpearls: true
  motd: You are in prison, enjoy your stay!
  unloadTimerTicks: 1200
ignore_feed:
  seconds: 0
  hours: 0
  days: 1
  feed_delay: 0
upkeep:
  resource: COAL_BLOCK
  quantity: 4
database:
  mysql:
    username: ''
    password: ''
    dbname: ''
    host: localhost
    port: 3306
    type: 1
